version: '3.8'

services:
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      # DB 연결 정보 (RDS 사용하는 경우)
      RDS_ENDPOINT: instagram-db.cpaecoyis85p.ap-northeast-2.rds.amazonaws.com
      RDS_USERNAME: admin
      RDS_PASSWORD: tjdrhks--123

      # Redis 설정 (같은 EC2에서 도커로 띄움)
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: 1234

      # 필수 설정 예시 (비워도 실행됨)
      JWT_SECRET: your-256-bit-secret-your-256-bit-secret-your-256-bit-secret
      AWS_S3_BUCKET: polysprings3bucket1
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY: polyspringuser
      AWS_SECRET_KEY: tjdrhks--123

      CORS_ALLOWED_ORIGINS: https://your-frontend.cloudfront.net
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - redis
    networks:
      - backend-net

  redis:
    image: redis:7.0
    container_name: redis-server
    command: redis-server --requirepass 1234
    volumes:
      - redis_data:/data
    networks:
      - backend-net

volumes:
  redis_data:

networks:
  backend-net:
